name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker login
      run: |
        docker login docker.pkg.github.com \
          --username punya-asapp \
          --password ${{ secrets.GITHUB_TOKEN }}

    - name: Find src commit
      run: |
        # Find the most recent commit that touched something outside helm-charts
        src_commit=$(git log -1 --pretty=format:%h :^helm-charts)

        # Describe it nicely if possible
        src_commit=$(git describe --tags --always $src_commit)

        app_version=git-$src_commit

        echo "::set-env name=app_version::$app_version"

    - name: Build image
      run: |
        image_tag=docker.pkg.github.com/punya-asapp/chart-example/hello:$app_version

        if [ docker pull $image_tag ]; then
          echo "Image already exists, skipping"
          exit 0
        fi

        docker build . -f ./docker/hello/Dockerfile -t temp_image

        # Tag the temporary image
        docker tag temp_image $image_tag

    - name: Publish image
      run: |
        if [ $GITHUB_REF = refs/heads/master ]; then
          docker push $image_tag
        else
          echo "Skipping publish step because we aren't on master"
        fi

    - name: Inject image tag into chart
      run: |
        rm -rf ./dist
        mkdir -p dist
        cp -r helm-charts dist/
        sed "s/REPLACE_ME_APP_VERSION/$app_version/g" --in-place="" dist/helm-charts/hello/Chart.yaml
        tar -C dist/helm-charts -zcf dist/hello.tgz hello

    - name: Archive charts
      uses: actions/upload-artifact@v1
      with:
        name: chart
        path: dist/hello.tgz
